install:
  - appveyor-retry appveyor DownloadFile https://win.rustup.rs/ -FileName rustup-init.exe
  - echo Building %TARGET%-%CHANNEL%
  - rustup-init.exe -y --default-host %TARGET% --default-toolchain %CHANNEL%
  - set PATH=%PATH%;C:\Users\appveyor\.cargo\bin
  - rustc --version --verbose
  - cargo --version --verbose

build: false

test_script:
  - cargo test --test test -- --nocapture
  - cargo test --test test --release -- --nocapture

environment:
  matrix:
    # Stable
    - channel: stable
      target: x86_64-pc-windows-msvc
    - channel: stable
      target: i686-pc-windows-msvc
    - channel: stable
      target: x86_64-pc-windows-gnu
    - channel: stable
      target: i686-pc-windows-gnu

    # Beta
    - channel: beta
      target: x86_64-pc-windows-msvc
    - channel: beta
      target: i686-pc-windows-msvc
    - channel: beta
      target: x86_64-pc-windows-gnu
    - channel: beta
      target: i686-pc-windows-gnu

    # Nightly
    - channel: nightly
      target: x86_64-pc-windows-msvc
    - channel: nightly
      target: i686-pc-windows-msvc
    - channel: nightly
      target: x86_64-pc-windows-gnu
    - channel: nightly
      target: i686-pc-windows-gnu

matrix:
  allow_failures:
    - channel: nightly