language: rust
sudo: false

rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly

script:
  - cargo test --test test -- --nocapture
  - cargo test --test test --release -- --nocapture